name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build React and Deploy to GitHub Pages
    runs-on: ubuntu-latest
    container:
      image: nikolaik/python-nodejs:python3.11-nodejs20-bullseye
    steps:
      - uses: actions/checkout@v3
      - name: Install and Version Check
        run: |
          echo "node version"
          node -v
          echo "yarn version"
          yarn -v
      - name: Install Dependencies
        run: yarn install
      - name: Build and Export
        run: yarn export
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
